project 'FRun.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FRun' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'Follower', '~> 0.1'
  # Pods for FRun

  target 'FRunTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FRunUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
