project 'BuldingMall.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'BuldingMall' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   
pod 'MBProgressHUD', '~> 0.8'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'MJRefresh', '~> 2.4.8'
pod 'MJExtension', '~> 2.5.10'
pod 'SDWebImage', '~> 3.7.3'
pod 'MKNetworkKit','~> 0.87'

# Pods 百度统计
pod 'BaiduMobStat','~> 4.1.0'
  # Pods for BuldingMall

  target 'BuldingMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuldingMallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
